---
title: "Course Project"
output: pdf_document
---
================================================

Let's simulate the exponential distribution! We have 40 samples, each with **lambda** values of 0.2. Let's run this with 2500 trials (simulations).

```{r}
set.seed(12312412) # random seed
library(ggplot2) # plotting 

lambda <- 0.2
n_samples <- 40 
n_sims <- 2500
mu <- apply(matrix(rexp(n_samples*n_sims, lambda), n_sims), 1, mean) #sample means
mean_mu <- mean(mu) # mean of sample means
mu_theor <- 1/lambda #theoretical mean
var_mu <- var(mu) #variance of sample means
var_theor <- 1/(n_samples*lambda^2)
```
Now let's make the plot object using **ggplot**. 

```{r}
g <- ggplot(data=data.frame(mu), aes(x=mu)) 
geom_histogram(aes(y=..density..), binwidth=0.1, fill='lightblue', colour='black') 
geom_density(colour="blue")+   stat_function(fun=dnorm, colour="red", size=1,
            args=list(mean=5,sd=1/(lambda)*(1/sqrt(n_samples)))
             
xlab("Means") + ylab("") 
ggtitle("Means of Samples from Exponential Distribution")  
annotate("text", x=c(7.4,7.5),  y=c(0.5,0.55), size=3,
          label=c("Uniform Density", "Density of samples")) 
annotate("segment", x = c(6.2,6.2), xend = c(6.4,6.4), y  = c(0.5,0.55), 
          yend = c(0.5,0.55),colour = c("red", "blue"))


```

